//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfWODCoach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public int athlete_id { get; set; }
        public int wod_id { get; set; }
        public Nullable<float> rating { get; set; }
        public string comment { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
    
        public virtual Athlete Athlete { get; set; }
        public virtual Wod Wod { get; set; }
    }
}
