//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfWODCoach.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WODCoachEntities : DbContext
    {
        public WODCoachEntities()
            : base("name=WODCoachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Athlete> Athlete { get; set; }
        public virtual DbSet<Coach> Coach { get; set; }
        public virtual DbSet<Rate> Rate { get; set; }
        public virtual DbSet<Wod> Wod { get; set; }
    }
}
