//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfWODCoach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Athlete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Athlete()
        {
            this.Wod = new HashSet<Wod>();
            this.Rate = new HashSet<Rate>();
        }
    
        public int idAthlete { get; set; }
        public string fullname { get; set; }
        public string telNumber { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
        public int Coach_idCoach { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wod> Wod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rate> Rate { get; set; }
        public virtual Coach Coach { get; set; }
    }
}
