//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfWODCoach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wod()
        {
            this.Rate = new HashSet<Rate>();
        }
    
        public int idWod { get; set; }
        public string movementName { get; set; }
        public Nullable<int> repsCount { get; set; }
        public Nullable<int> roundCount { get; set; }
        public Nullable<float> level { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> done { get; set; }
        public string comment { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
        public Nullable<int> idAthlete { get; set; }
    
        public virtual Athlete Athlete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rate> Rate { get; set; }
    }
}
